### ISSUE TITLE
update build to create png from svgs

### ISSUE THREAD

**Issue by elliemcopeland** [elliemcopeland/email-signatures#12]
for all icons: 
- [ ] logo
- [ ] social medias (4)
- [ ] nikon

**Comment by Sporkyy** [comment]
Nope. Tried it and it just hung there.

**Comment by elliemcopeland** [comment]
lol so should i modify this to say "update svgs to be pngs" and assign to me? :)

**Comment by Sporkyy** [comment]
No, I already did it and sent a pull request.
